services:
  app:
    image: node:latest
    container_name: logisticslink
    working_dir: /logisticslink
    volumes:
      - .:/logisticslink
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: sh -c 'npm install && npm start'
    restart: always
